// <auto-generated />
using BotManager.Backend.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BotManager.Backend.Entities.Migrations
{
    [DbContext(typeof(BotManagerDbContext))]
    [Migration("20260304194648_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.Bot", b =>
                {
                    b.Property<int>("BotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BotId"));

                    b.Property<string>("BotToken")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BotId");

                    b.ToTable("Bots");
                });

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.BotConfiguration", b =>
                {
                    b.Property<int>("BotId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ReactionChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal?>("RoleMessageId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal?>("TeamsMessageId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("BotId");

                    b.ToTable("BotConfigurations");
                });

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<string>("CommanderContact")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.BotConfiguration", b =>
                {
                    b.HasOne("BotManager.Backend.Entities.Entities.Bot", "Bot")
                        .WithOne("Configuration")
                        .HasForeignKey("BotManager.Backend.Entities.Entities.BotConfiguration", "BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bot");
                });

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.Bot", b =>
                {
                    b.Navigation("Configuration")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
