// <auto-generated />
using System;
using BotManager.Backend.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BotManager.Backend.Entities.PostgreSql.Migrations
{
    [DbContext(typeof(BotManagerDbContext))]
    partial class BotManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.AdminAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ActorEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TargetId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TargetType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("TargetType", "TargetId");

                    b.ToTable("AdminAuditLogs");
                });

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.BoardConfiguration", b =>
                {
                    b.Property<int>("BoardConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BoardConfigurationId"));

                    b.Property<decimal?>("BoardChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("BoardDescriptionTemplate")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("BoardMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("BoardTitle")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("BoardType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("BotId")
                        .HasColumnType("integer");

                    b.Property<string>("ContactLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("SubtitleLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("BoardConfigurationId");

                    b.HasIndex("BotId");

                    b.ToTable("BoardConfigurations");
                });

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.BoardGlobalConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultBoardDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DefaultBoardDetailContactLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DefaultBoardDetailSubtitleLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DefaultBoardTitle")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.ToTable("BoardGlobalConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultBoardDescription = "Celkem registrovaných skupin: {count}",
                            DefaultBoardDetailContactLabel = "Kontakt",
                            DefaultBoardDetailSubtitleLabel = "Podtitul",
                            DefaultBoardTitle = "📋 Seznam všech skupin"
                        });
                });

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.Bot", b =>
                {
                    b.Property<int>("BotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BotId"));

                    b.Property<bool>("AutoStart")
                        .HasColumnType("boolean");

                    b.Property<string>("BotToken")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastStartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastStoppedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("BotId");

                    b.ToTable("Bots");
                });

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.BotCommand", b =>
                {
                    b.Property<int>("CommandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommandId"));

                    b.Property<string>("AdminOnlyMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("BotId")
                        .HasColumnType("integer");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CommandParameters")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("InvalidArgumentsMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("MinimumPermissionLevel")
                        .HasColumnType("integer");

                    b.Property<string>("PermissionMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SubCommandName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SuccessMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserHint")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("CommandId");

                    b.HasIndex("BotId", "CommandName", "SubCommandName");

                    b.ToTable("BotCommands");
                });

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.BotConfiguration", b =>
                {
                    b.Property<int>("BotId")
                        .HasColumnType("integer");

                    b.Property<int?>("ActiveBoardConfigurationId")
                        .HasColumnType("integer");

                    b.HasKey("BotId");

                    b.HasIndex("ActiveBoardConfigurationId");

                    b.ToTable("BotConfigurations");
                });

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.BotRunHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BotId")
                        .HasColumnType("integer");

                    b.Property<long?>("DurationSeconds")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorDetails")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("StopReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("StoppedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BotId");

                    b.ToTable("BotRunHistories");
                });

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.CommandUsageLog", b =>
                {
                    b.Property<int>("UsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsageId"));

                    b.Property<int>("CommandId")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UsageId");

                    b.HasIndex("ExecutedAt");

                    b.HasIndex("CommandId", "ExecutedAt");

                    b.ToTable("CommandUsageLogs");
                });

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.LoginAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FailReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsBruteforceBlock")
                        .HasColumnType("boolean");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("LoginAuditLogs");
                });

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("Email", "ExpiresAt");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.SystemConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("SystemConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Maximum failed login attempts before lockout",
                            Key = "Bruteforce.MaxAttempts",
                            Value = "5"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Minutes to lock out after too many failures",
                            Key = "Bruteforce.LockoutMinutes",
                            Value = "5"
                        });
                });

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.SystemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BotId")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Exception")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("BotId", "Timestamp");

                    b.ToTable("SystemLogs");
                });

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TeamId"));

                    b.Property<int>("BoardConfigurationId")
                        .HasColumnType("integer");

                    b.Property<string>("CommanderContact")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LeaderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("TeamId");

                    b.HasIndex("BoardConfigurationId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.BoardConfiguration", b =>
                {
                    b.HasOne("BotManager.Backend.Entities.Entities.Bot", "Bot")
                        .WithMany("BoardConfigurations")
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bot");
                });

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.BotCommand", b =>
                {
                    b.HasOne("BotManager.Backend.Entities.Entities.Bot", "Bot")
                        .WithMany("Commands")
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bot");
                });

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.BotConfiguration", b =>
                {
                    b.HasOne("BotManager.Backend.Entities.Entities.BoardConfiguration", "ActiveBoardConfiguration")
                        .WithMany()
                        .HasForeignKey("ActiveBoardConfigurationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BotManager.Backend.Entities.Entities.Bot", "Bot")
                        .WithOne("Configuration")
                        .HasForeignKey("BotManager.Backend.Entities.Entities.BotConfiguration", "BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveBoardConfiguration");

                    b.Navigation("Bot");
                });

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.BotRunHistory", b =>
                {
                    b.HasOne("BotManager.Backend.Entities.Entities.Bot", "Bot")
                        .WithMany("Histories")
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bot");
                });

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.CommandUsageLog", b =>
                {
                    b.HasOne("BotManager.Backend.Entities.Entities.BotCommand", "BotCommand")
                        .WithMany("UsageLogs")
                        .HasForeignKey("CommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BotCommand");
                });

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.Team", b =>
                {
                    b.HasOne("BotManager.Backend.Entities.Entities.BoardConfiguration", "BoardConfiguration")
                        .WithMany("Teams")
                        .HasForeignKey("BoardConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardConfiguration");
                });

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.BoardConfiguration", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.Bot", b =>
                {
                    b.Navigation("BoardConfigurations");

                    b.Navigation("Commands");

                    b.Navigation("Configuration");

                    b.Navigation("Histories");
                });

            modelBuilder.Entity("BotManager.Backend.Entities.Entities.BotCommand", b =>
                {
                    b.Navigation("UsageLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
